package com.family.tracker.parent
import android.app.*; import android.content.BroadcastReceiver; import android.content.Context; import android.content.Intent; import android.content.IntentFilter; import android.graphics.PixelFormat; import android.os.IBinder; import android.view.*; import android.widget.ImageView; import org.osmdroid.config.Configuration; import org.osmdroid.tileprovider.tilesource.TileSourceFactory; import org.osmdroid.util.GeoPoint; import org.osmdroid.views.MapView; import org.osmdroid.views.overlay.Marker; import java.io.File
class FloatingMapService:Service(){private var wm:WindowManager?=null;private var view:View?=null;private var map:MapView?=null;private var marker:Marker?=null
private val rec=object:BroadcastReceiver(){override fun onReceive(c:Context?,i:Intent?){val lat=i?.getDoubleExtra("lat",0.0)?:return;val lon=i?.getDoubleExtra("lon",0.0)?:return;if(lat==0.0&&lon==0.0)return;try{val p=GeoPoint(lat,lon);marker?.position=p;map?.controller?.animateTo(p);map?.invalidate()}catch(_:Exception){}}}
override fun onBind(i:Intent?):IBinder?=null;override fun onCreate(){super.onCreate();val c=NotificationChannel("floating_map","Carte Flottante",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager::class.java).createNotificationChannel(c);Configuration.getInstance().apply{userAgentValue="TrackerParent/1.0";osmdroidBasePath=File(cacheDir,"osmdroid");osmdroidTileCache=File(cacheDir,"osmdroid/tiles")}}
override fun onStartCommand(i:Intent?,f:Int,s:Int):Int{startForeground(3,Notification.Builder(this,"floating_map").setContentTitle("Mini-carte active").setSmallIcon(android.R.drawable.ic_dialog_map).setOngoing(true).build());if(view==null)createWindow();registerReceiver(rec,IntentFilter("TRACKER_UPDATE"),RECEIVER_NOT_EXPORTED);return START_STICKY}
private fun createWindow(){wm=getSystemService(Context.WINDOW_SERVICE)as WindowManager;val inf=getSystemService(Context.LAYOUT_INFLATER_SERVICE)as LayoutInflater;view=inf.inflate(R.layout.floating_map,null);map=view!!.findViewById(R.id.floatingMap);map!!.setTileSource(TileSourceFactory.MAPNIK);map!!.setMultiTouchControls(true);map!!.controller.setZoom(17.0);map!!.controller.setCenter(GeoPoint(47.4736,-0.5517));marker=Marker(map).apply{position=GeoPoint(47.4736,-0.5517);title="Enfant"};map!!.overlays.add(marker)
view!!.findViewById<ImageView>(R.id.btnClose).setOnClickListener{stopSelf()};view!!.findViewById<ImageView>(R.id.btnExpand).setOnClickListener{startActivity(Intent(this,MapActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))}
val p=WindowManager.LayoutParams(350,350,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL,PixelFormat.TRANSLUCENT);p.gravity=Gravity.TOP or Gravity.START;p.x=20;p.y=150
var ix=0;var iy=0;var tx=0f;var ty=0f
view!!.findViewById<View>(R.id.dragHandle).setOnTouchListener{_,e->when(e.action){MotionEvent.ACTION_DOWN->{ix=p.x;iy=p.y;tx=e.rawX;ty=e.rawY;true}MotionEvent.ACTION_MOVE->{p.x=ix+(e.rawX-tx).toInt();p.y=iy+(e.rawY-ty).toInt();wm?.updateViewLayout(view,p);true}else->false}}
wm?.addView(view,p)}
override fun onDestroy(){super.onDestroy();try{unregisterReceiver(rec)}catch(_:Exception){};try{map?.onPause()}catch(_:Exception){};if(view!=null)try{wm?.removeView(view)}catch(_:Exception){};view=null}}
