package com.family.tracker.parent
import android.Manifest; import android.content.*; import android.content.pm.PackageManager; import android.graphics.BitmapFactory; import android.net.Uri; import android.os.Bundle; import android.provider.Settings; import android.telephony.SmsManager; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import androidx.core.app.ActivityCompat; import com.google.android.material.floatingactionbutton.FloatingActionButton; import org.osmdroid.config.Configuration; import org.osmdroid.tileprovider.tilesource.TileSourceFactory; import org.osmdroid.util.GeoPoint; import org.osmdroid.views.MapView; import org.osmdroid.views.overlay.Marker; import java.io.File; import java.net.NetworkInterface; import java.util.*
class MapActivity:AppCompatActivity(){private lateinit var map:MapView;private var marker:Marker?=null;private lateinit var status:TextView;private lateinit var srvUrl:TextView;private lateinit var photoView:ImageView;private val parentNum="$PARENT_NUM"
private val locRec=object:BroadcastReceiver(){override fun onReceive(c:Context?,i:Intent?){val lat=i?.getDoubleExtra("lat",0.0)?:return;val lon=i?.getDoubleExtra("lon",0.0)?:return;if(lat==0.0&&lon==0.0)return;runOnUiThread{val p=GeoPoint(lat,lon);marker?.position=p;map.controller.animateTo(p);map.controller.setZoom(17.0);map.invalidate();val df=java.text.SimpleDateFormat("HH:mm:ss",Locale.FRANCE);status.text="✅ Position: $lat, $lon - ${df.format(Date())}"}}}
private val phoRec=object:BroadcastReceiver(){override fun onReceive(c:Context?,i:Intent?){val d=i?.getByteArrayExtra("photo_data")?:return;runOnUiThread{val b=BitmapFactory.decodeByteArray(d,0,d.size);photoView.setImageBitmap(b);photoView.visibility=android.view.View.VISIBLE;Toast.makeText(this@MapActivity,"📷 Photo reçue !",Toast.LENGTH_SHORT).show()}}}
override fun onCreate(s:Bundle?){super.onCreate(s);val cfg=Configuration.getInstance();cfg.userAgentValue="TrackerParent/1.0";cfg.osmdroidBasePath=File(cacheDir,"osmdroid");cfg.osmdroidTileCache=File(cacheDir,"osmdroid/tiles");setContentView(R.layout.activity_map)
map=findViewById(R.id.map);status=findViewById(R.id.status);srvUrl=findViewById(R.id.serverUrl);photoView=findViewById(R.id.receivedPhoto)
map.setTileSource(TileSourceFactory.MAPNIK);map.setMultiTouchControls(true);map.controller.setZoom(15.0);map.controller.setCenter(GeoPoint(47.4736,-0.5517));marker=Marker(map).apply{position=GeoPoint(47.4736,-0.5517);title="Enfant"};map.overlays.add(marker)
startService(Intent(this,PhotoHttpServerService::class.java));val ip=getLocalIP();srvUrl.text="Serveur photo: $ip:8904";srvUrl.setBackgroundColor(0xFF008800.toInt())
findViewById<FloatingActionButton>(R.id.fabCamera).setOnClickListener{if(ActivityCompat.checkSelfPermission(this,Manifest.permission.SEND_SMS)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,arrayOf(Manifest.permission.SEND_SMS,Manifest.permission.RECEIVE_SMS),101);return@setOnClickListener};try{SmsManager.getDefault().sendDataMessage(parentNum,null,8902.toShort(),"TAKE_PHOTO".toByteArray(),null,null);Toast.makeText(this,"📷 Commande envoyée",Toast.LENGTH_SHORT).show()}catch(e:Exception){Toast.makeText(this,"Erreur: ${e.message}",Toast.LENGTH_SHORT).show()}}
findViewById<FloatingActionButton>(R.id.fabFloat).setOnClickListener{if(!Settings.canDrawOverlays(this)){Toast.makeText(this,"Autorisez Afficher par-dessus",Toast.LENGTH_LONG).show();startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:$packageName")))}else{startForegroundService(Intent(this,FloatingMapService::class.java));Toast.makeText(this,"Mini-carte activée",Toast.LENGTH_LONG).show()}}}
private fun getLocalIP():String{try{val en=NetworkInterface.getNetworkInterfaces();while(en.hasMoreElements()){val intf=en.nextElement();val addrs=intf.inetAddresses;while(addrs.hasMoreElements()){val a=addrs.nextElement();if(!a.isLoopbackAddress&&a.hostAddress?.contains(":")==false)return a.hostAddress}}}catch(e:Exception){}return "???.???.???.???"}
override fun onResume(){super.onResume();try{map.onResume()}catch(_:Exception){};registerReceiver(locRec,IntentFilter("TRACKER_UPDATE"),RECEIVER_NOT_EXPORTED);registerReceiver(phoRec,IntentFilter("PHOTO_RECEIVED"),RECEIVER_NOT_EXPORTED)}
override fun onPause(){super.onPause();try{map.onPause()}catch(_:Exception){};try{unregisterReceiver(locRec)}catch(_:Exception){};try{unregisterReceiver(phoRec)}catch(_:Exception){}}}
